<!-- GitHub star -->
<a class="github-button" href="https://github.com/embark-framework/embark" data-icon="octicon-star" data-show-count="true" aria-label="Star embark-framework/embark on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/embark-framework/embark/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork embark-framework/embark on GitHub">Fork</a><!-- Tweet button -->
<!-- Twitter follow button -->
<a href="https://twitter.com/embarkframework" class="twitter-follow-button" data-show-count="true">Follow @embarkframework</a>
<!-- Github Button -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Twitter share button -->
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
